import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';

const OFFICIAL='https://www.fsgc.sm/it/campionato/campionato-sammarinese/1';
const FIXTURES='https://www.fsgc.sm/it/notizia/fixtures-tonights-draw-kicks-off-2026-27-season/2283';
const teams=['Virtus','La Fiorita','Tre Fiori','Tre Penne','Folgore/Falciano','Murata','Cailungo','Domagnano','San Marino Academy U22','Fiorentino','Juvenes/Dogana','Faetano','Cosmos','Libertas','Pennarossa','San Giovanni'];
const demoPlayers=[
 ['828','Manuel Ferrani','Tre Penne','DEF',8.0],['1036','Marco Andretta','Cosmos','MED',7.0],['1046','Giacomo Greco','Domagnano','MED',7.0],['1049','Benjamin Serifoski','La Fiorita','DEL',10.0],['419','Tommaso Guidi','La Fiorita','DEL',11.0],['543','Alex Ambrosini','Cosmos','DEL',9.0],['1034','Gianmario Piscitella','Virtus','DEL',10.0],['120','Matteo Vitaioli','La Fiorita','DEL',11.0],['901','Marseljan Mema','Tre Fiori','DEL',8.5],['429','Tommaso Leon Bernardi','Tre Fiori','DEL',10.5],['176','Nicko Sensoli','Tre Fiori','DEL',8.5],['731','Marco Gasperoni','Virtus','DEL',7.0]
].map(([id,name,team,pos,price])=>({id,name,team,pos,price}));
const fixtures=[
 ['28 AGO','Virtus','La Fiorita'],['28 AGO','Tre Fiori','Pennarossa'],['29 AGO','Tre Penne','San Giovanni'],['29 AGO','Folgore/Falciano','Murata'],['30 AGO','Cailungo','Domagnano'],['30 AGO','San Marino Academy U22','Fiorentino'],['30 AGO','Juvenes/Dogana','Faetano'],['30 AGO','Cosmos','Libertas']
];
const nav=[['home','Inicio','⌂'],['team','Mi equipo','⚽'],['market','Mercado','↗'],['leagues','Ligas','♛'],['players','Jugadores','♙'],['calendar','Calendario','▣']];
const SB_URL=import.meta.env.VITE_SUPABASE_URL; const SB_KEY=import.meta.env.VITE_SUPABASE_ANON_KEY; const sb=SB_URL&&SB_KEY?createClient(SB_URL,SB_KEY):null;
function euro(n){return `${n.toFixed(1)} M€`}
function App(){
 const [tab,setTab]=useState('home');
 const [squad,setSquad]=useState(()=>JSON.parse(localStorage.getItem('fsm_squad')||'[]'));
 const [league,setLeague]=useState(()=>JSON.parse(localStorage.getItem('fsm_league')||'null'));
 const [search,setSearch]=useState('');
 const [realPlayers,setRealPlayers]=useState([]); const [dataStatus,setDataStatus]=useState(sb?'Conectando con FSGC':'Sin Supabase configurado');
 const [teamFilter,setTeamFilter]=useState('Todos');
 const [toast,setToast]=useState('');
 const [formation,setFormation]=useState('4-3-3');
 const [session,setSession]=useState(null); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
 const budget=100;
 useEffect(()=>localStorage.setItem('fsm_squad',JSON.stringify(squad)),[squad]);
 useEffect(()=>league&&localStorage.setItem('fsm_league',JSON.stringify(league)),[league]);
 useEffect(()=>{if(!sb){setDataStatus('Sin Supabase configurado');return;} sb.auth.getSession().then(({data})=>setSession(data.session)); const {data:sub}=sb.auth.onAuthStateChange((_e,session)=>setSession(session)); return ()=>sub.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!sb){setDataStatus('Sin Supabase configurado');return;} sb.from('players').select('id,name,club,position,price,official_url').eq('active',true).order('name').then(({data,error})=>{if(error){setDataStatus('Error de datos');return;} setRealPlayers((data||[]).map(p=>({id:String(p.id),name:p.name,team:p.club,pos:p.position,price:Number(p.price)/1000000,fsgc_url:p.official_url}))); setDataStatus(`Supabase · ${data?.length||0} jugadores`);});},[]);;
 const spent=squad.reduce((sum,id)=>sum+(sourcePlayers.find(p=>p.id===id)?.price||0),0);
 const available=budget-spent;
 const sourcePlayers=realPlayers.length?realPlayers:demoPlayers; const players=sourcePlayers.filter(p=>(teamFilter==='Todos'||p.team===teamFilter)&&`${p.name} ${p.team} ${p.pos}`.toLowerCase().includes(search.toLowerCase()));
 const flash=t=>{setToast(t);setTimeout(()=>setToast(''),2200)};
 const buy=async p=>{if(squad.includes(p.id))return flash('Ya tienes este jugador.');if(squad.length>=14)return flash('Máximo 14 jugadores.');if(available<p.price)return flash('No tienes presupuesto suficiente.'); if(sb&&session){let teamId; const {data:t}=await sb.from('teams').select('id').eq('user_id',session.user.id).limit(1).maybeSingle(); if(t) teamId=t.id; else {const {data:nt,error}=await sb.from('teams').insert({user_id:session.user.id,name:'Mi Fantasy',budget:budget,formation}).select('id').single(); if(error)return flash('No se pudo crear tu equipo.'); teamId=nt.id;} const {error}=await sb.from('team_players').insert({team_id:teamId,player_id:p.id,bought_for:p.price}); if(error)return flash('No se pudo fichar en Supabase.');} setSquad([...squad,p.id]);flash(`${p.name} fichado.`)};
 const createLeague=async()=>{const code=Math.random().toString(36).slice(2,8).toUpperCase(); if(sb&&session){const {data,error}=await sb.from('leagues').insert({name:'Liga de amigos',invite_code:code,owner_id:session.user.id}).select('id,name,invite_code').single(); if(error)return flash('Inicia sesión para crear la liga.'); await sb.from('league_members').insert({league_id:data.id,user_id:session.user.id}); setLeague({id:data.id,name:data.name,code:data.invite_code,members:[{name:'Tú',points:0}]});}else setLeague({name:'Liga local',code,members:[{name:'Tú',points:0}]}); flash(`Liga creada: ${code}`)};
 const auth=async()=>{if(!sb)return flash('Supabase no configurado.'); const {error}=await sb.auth.signUp({email,password}); if(error)return flash(error.message); flash('Revisa tu correo para confirmar la cuenta.');};
 return <div className="app">
  <header><button className="mobile-logo" onClick={()=>setTab('home')}>🇸🇲</button><div className="logo"><div className="logo-mark">SM</div><div><b>FANTA SAN MARINO</b><small>Campionato Sammarinese · 2026/27</small></div></div><div className="verified"><span/> Fuente principal: FSGC <a href={OFFICIAL} target="_blank">ver</a></div><div className="user">{session?'✓':'A'}</div></header>{!session&&<div className="auth-strip"><span>Conecta tu cuenta para guardar tu equipo y ligas online.</span><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="contraseña"/><button className="primary small" onClick={auth}>Crear cuenta</button></div>}
  <div className="layout"><aside><div className="season">TEMPORADA ACTIVA<strong>2026/27</strong></div>{nav.map(([id,label,icon])=><button key={id} className={tab===id?'nav active':'nav'} onClick={()=>setTab(id)}><i>{icon}</i>{label}</button>)}<div className="sync-card"><div className="sync-dot"/><b>Datos trazables</b><p>Los resultados oficiales se guardan con fuente, fecha y estado de confirmación.</p><a href={OFFICIAL} target="_blank">FSGC oficial ↗</a></div></aside>
   <main>{toast&&<div className="toast">✓ {toast}</div>}{tab==='home'&&<Home setTab={setTab} squad={squad} available={available} league={league}/>} {tab==='team'&&<Team squad={squad} players={sourcePlayers} formation={formation} setFormation={setFormation}/>} {tab==='market'&&<Market players={players} search={search} setSearch={setSearch} teamFilter={teamFilter} setTeamFilter={setTeamFilter} buy={buy} available={available}/>} {tab==='leagues'&&<Leagues league={league} create={createLeague} flash={flash}/>} {tab==='players'&&<Players players={players} search={search} setSearch={setSearch}/>} {tab==='calendar'&&<Calendar/>}</main>
  </div><footer><span>Fanta San Marino</span><span>Datos: <b>{dataStatus}</b></span><span>2026</span></footer>
 </div>
}
function Home({setTab,squad,available,league}){return <><section className="hero"><div><span className="eyebrow">FANTASY OFICIALMENTE TRAZABLE</span><h1>El fantasy del<br/><em>fútbol de San Marino.</em></h1><p>Construye tu equipo, ficha jugadores y compite con tus amigos. Los resultados de partido se validan primero contra la FSGC.</p><div className="hero-actions"><button className="primary" onClick={()=>setTab('market')}>Empezar a fichar →</button><button className="ghost" onClick={()=>setTab('leagues')}>{league?'Ver mi liga':'Crear una liga'}</button></div></div><div className="hero-panel"><span>JORNADA 1</span><b>28–30</b><strong>AGO 2026</strong><div className="hero-stats"><div><b>100</b><small>M€</small></div><div><b>{squad.length}</b><small>PLANTILLA</small></div><div><b>{available.toFixed(1)}</b><small>DISPONIBLE</small></div></div></div></section><div className="stats"><Stat n="0" l="PUNTOS" s="Jornada 1"/><Stat n={`${squad.length}/14`} l="PLANTILLA" s="Jugadores"/><Stat n={euro(available)} l="PRESUPUESTO" s="Disponible"/><Stat n="0" l="LIGAS" s="Esta temporada"/></div><div className="columns"><Card title="Primera jornada" action="Calendario →" onAction={()=>setTab('calendar')}><div className="fixture-list">{fixtures.slice(0,5).map((f,i)=><Fixture key={i} f={f}/>)}</div></Card><Card title="Cómo funciona"><Rule n="01" t="Fichas" d="Empieza con 100 M€ y construye una plantilla de hasta 14 jugadores."/><Rule n="02" t="Puntúas" d="El motor convierte estadísticas de partido en puntos fantasy cuando la jornada se cierra."/><Rule n="03" t="Compites" d="Crea una liga privada y comparte un código con tus amigos."/></Card></div><div className="source-banner"><div className="source-icon">✓</div><div><b>Fuente de resultados: Federazione Sammarinese Giuoco Calcio</b><p>La FSGC ha fijado la primera jornada 2026/27 para el fin de semana del 28–30 de agosto de 2026.</p></div><a href={FIXTURES} target="_blank">Comprobar fuente ↗</a></div></>}
function Stat({n,l,s}){return <div className="stat"><span>{l}</span><b>{n}</b><small>{s}</small></div>}
function Card({title,action,onAction,children}){return <section className="card"><div className="card-title"><h2>{title}</h2>{action&&<button onClick={onAction}>{action}</button>}</div>{children}</section>}
function Rule({n,t,d}){return <div className="rule"><b>{n}</b><div><strong>{t}</strong><p>{d}</p></div></div>}
function Fixture({f}){return <div className="fixture"><small>{f[0]}</small><b>{f[1]}</b><span>vs</span><b>{f[2]}</b><i>—</i></div>}
function Team({squad,players,formation,setFormation}){const picked=squad.map(id=>players.find(p=>p.id===id)).filter(Boolean);const rows={ '4-3-3':[1,4,3,3], '3-5-2':[1,3,5,2], '4-4-2':[1,4,4,2], '3-4-3':[1,3,4,3]};return <><PageHead tag="MI EQUIPO" title="Mi plantilla" text="Elige formación y prepara tu once." right={<div className="money-box"><small>DISPONIBLE</small><b>{euro(100-picked.reduce((a,p)=>a+p.price,0))}</b></div>}/><div className="formations">{Object.keys(rows).map(x=><button className={x===formation?'selected':''} onClick={()=>setFormation(x)} key={x}>{x}</button>)}</div><div className="pitch">{rows[formation].map((count,r)=><div className="pitch-row" key={r}>{Array.from({length:count},(_,i)=>{const p=picked[(r*3+i)%Math.max(picked.length,1)];return <div className="pitch-player" key={i}><div className="player-circle">{p?'⚽':'+'}</div><b>{p?p.name.split(' ')[2]||p.name.split(' ')[0]:'Vacío'}</b><small>{p?.pos||'POS'}</small></div>})}</div>)}</div><Card title={`Plantilla · ${picked.length}/14`}><div className="table">{picked.length?picked.map(p=><div className="table-row" key={p.id}><b>{p.name}</b><span>{p.team}</span><span>{p.pos}</span><strong>{euro(p.price)}</strong></div>):<div className="empty">No tienes jugadores todavía. Ve al Mercado para empezar.</div>}</div></Card></>}
function PageHead({tag,title,text,right}){return <div className="page-head"><div><span className="eyebrow">{tag}</span><h1>{title}</h1><p>{text}</p></div>{right}</div>}
function Market({players,search,setSearch,teamFilter,setTeamFilter,buy,available}){return <><PageHead tag="MERCADO" title="Fichajes" text="Encuentra jugadores y controla tu presupuesto." right={<div className="money-box"><small>DISPONIBLE</small><b>{euro(available)}</b></div>}/><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar jugador o equipo..."/><select value={teamFilter} onChange={e=>setTeamFilter(e.target.value)}><option>Todos</option>{teams.map(t=><option key={t}>{t}</option>)}</select></div>{!realPlayers.length&&<div className="demo-warning">⚠ La interfaz está en modo local. Configura Supabase para cargar automáticamente el registro real de jugadores de la FSGC y sus enlaces oficiales.</div>}<div className="player-grid">{players.map(p=><article className="player-card" key={p.id}><div className="player-meta"><span>{p.pos}</span><small>{p.team}</small></div><div className="avatar-ball">⚽</div><h3>{p.name}</h3><p>{p.team}</p><div className="player-price"><b>{euro(p.price)}</b><button className="primary small" onClick={()=>buy(p)}>Fichar</button></div></article>)}</div></>}
function Players({players,search,setSearch}){return <><PageHead tag="BASE DE DATOS" title="Jugadores" text="Ranking y valores fantasy."/><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar..."/></div><Card title="Ranking"><div className="table table-head"><span>Jugador</span><span>Equipo</span><span>Posición</span><span>Valor</span></div>{players.map((p,i)=><div className="table-row" key={p.id}><b>#{i+1} · {p.name}</b><span>{p.team}</span><span>{p.pos}</span><strong>{euro(p.price)}</strong></div>)}</Card></>}
function Leagues({league,create,flash}){const join=()=>{const c=prompt('Código de invitación');if(!c)return;if(c.trim().toUpperCase()===(league?.code||'NONE'))flash('Ya estás en esta liga.');else flash('En producción, este código buscará la liga en Supabase.')};return <><PageHead tag="COMPETICIÓN" title="Mis ligas" text="Ligas privadas para competir con tus amigos." right={<div className="hero-actions"><button className="ghost" onClick={join}>Unirme con código</button><button className="primary" onClick={create}>Crear liga</button></div>}/>{league?<div className="columns"><Card title={league.name}><div className="invite"><small>CÓDIGO</small><b>{league.code}</b><button onClick={()=>navigator.clipboard?.writeText(league.code)}>Copiar código</button></div></Card><Card title="Clasificación"><div className="standings">{league.members.map((m,i)=><div className="standing" key={i}><b>{i+1}</b><span>{m.name}</span><strong>{m.points} pts</strong></div>)}</div></Card></div>:<div className="empty big"><b>Aún no tienes ninguna liga</b><p>Crea una y comparte el código con tus amigos.</p><button className="primary" onClick={create}>Crear mi liga</button></div>}</>}
function Calendar(){return <><PageHead tag="FSGC · CALENDARIO" title="Campionato Sammarinese 2026/27" text="Primera jornada: 28–30 de agosto de 2026." right={<a className="source-btn" href={FIXTURES} target="_blank">Fuente oficial ↗</a>}/><Card title="Jornada 1"><div className="fixture-list">{fixtures.map((f,i)=><Fixture f={f} key={i}/>)}</div></Card><div className="source-banner"><div className="source-icon">F</div><div><b>Sincronización de resultados</b><p>Prioridad: FSGC. Una segunda fuente puede servir para detectar discrepancias, pero el resultado oficial manda.</p></div><a href={OFFICIAL} target="_blank">Abrir FSGC ↗</a></div></>}
createRoot(document.getElementById('root')).render(<App/>);
